tildeio/route-recognizer

package.json
I actually can't even `npm install` this project right now as-is because `v0.0.40` contained an `expresss` typo [found here](https://github.com/ember-cli/ember-cli/blob/v0.0.40/package.json#L58).
```bash
npm ERR! 404 Not Found: expresss
npm ERR! 404
npm ERR! 404 'expresss' is not in the npm registry.
```
It also doesn't hurt to bump it too :trophy:
=> Bumped to ember-cli@v0.1.7 to fix npm install

lib/route-recognizer.js, tests/recognizer-tests.js
Fixes https://github.com/emberjs/ember.js/issues/10190
http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1
Facebook's share redirect masking is a great way to confirm this issue and behavior. (note that even query keys can have encoded spaces)
Cc/ @machty
=> [BUGFIX] Query param plus symbols (+) are now transformed to spaces

lib/route-recognizer.js, tests/recognizer-tests.js
The current sorting algorithm *works-ish*, but it's a bit odd. Firstly, [it is imperfect.](https://github.com/tildeio/route-recognizer/blob/master/lib/route-recognizer.js#L232) Secondly, [it is rather complicated.](https://github.com/tildeio/route-recognizer/blob/master/lib/route-recognizer.js#L243-L253)
This PR takes advantage of a symmetry between route sorting and the way we represent numberz as symbols. Whenever you write numbers in base10, subsequent additions to the left increase the size of the number by an order of magnitude, thus ensuring that the number is larger. In other words, any number written as `xyz` is larger than any other number written as `ab` assuming `x > 0, a > 0`. Such is the case with URLs and specificity; URLs with more segments are *always* more specific (think …
=> Implement a smarter route match algorithm.

dist/route-recognizer.js
Temporary fix for Issue #44, which is that the Ember CLI complains that it needs a source map that it can't find.
=> Stop the Ember CLI from asking for the source map

lib/route-recognizer.umd.js
Loader like almond needs the name to be passed for to the define function.
This is related to #49
=> add name parameter to amd define function call

README.md
`RouteRecognizer#add` does not accept an object as an argument; it only accepts an array.
=> Fix example in documentation.

lib/route-recognizer.js, tests/recognizer-tests.js, tests/router-tests.js
when a queryParam is malformed `?foo=bar%` an error is thrown `URIError: URI malformed` this commit handles the error and ignores the value of the queryParam
=> handle malformed URI error

dist/route-recognizer.js, lib/route-recognizer.js
Speed up of about ~30 op/s consistently overall. 5000 op/s improvement around `recognize`. Tried using an object that was placed into dictionary mode for the cache as the shape changes overtime but seemed slower.
```
Add ................... 505.78 op/s
End-to-end ............ 270.97 op/s
Generate ........ 4,874,011.82 op/s
Handlers For ... 37,588,869.18 op/s
Recognize ......... 360,278.12 op/s
```
=> [PERF] Cache results of State.get

lib/route-recognizer.js, tests/recognizer-tests.js
Fixes #82 , supersedes #83
---
This PR is fixing a lil mistake I made when I updated the route sorting algorithm in #46.
This change might seem arbitrary, so let me explain the mistake I made, how this fixes it, and a caveat. That way, it can be merged with confidence :fist:
LET'S GET TO IT
When I wrote this algorithm, I used these definitions:
**Epsilon segment** = empty segment (0 characters)
**Glob segment** = empty *or* non-empty segment = (0 or more characters)
The sorting algorithm that I'm using gives routes a numeric value to sort them by. Larger numbers are more specific. Trying to give these two segment types a single value is not straightforward, because glob segments have two interesting states – they're either empty or they're not – and we may want to take those into account …
=> Resolve issue where globs would be prioritized over empty segments

lib/route-recognizer.js
route-recognizer originally used a Rakefile to build that had a [replace_debug method](https://github.com/tildeio/route-recognizer/blob/fa15bd6ad0f9ff2f07e2df5b94ca6a07fe22e12a/Rakefile#L3-L13) that would conditionally turn the `// DEBUG` lines into console logs, but when the build system [changed to broccoli](https://github.com/tildeio/route-recognizer/commit/efc828d426f2ae9b21c0c27ebf61f4a150a6a67f#diff-52c976fc38ed2b4e3b1192f8a8e24cffL6) the debug build was removed. These `// DEBUG` comments in the code are thus no longer used.
=> Remove commented DEBUG statements

Brocfile.js, bench/benches/normalize.js, bench/index.js, lib/route-recognizer.js, lib/route-recognizer/normalizer.js, tests/normalizer-tests.js, tests/recognizer-tests.js
This PR supersedes #55. That PR originally attempted to encode/decode dynamic segments in matched paths, but it grew much larger when I attempted to make the solution robust in the face of dynamic segments with percent-encoded percent characters (`encodeURI("%") === "%25"`).
I'm approaching this PR in the spirit of an RFC, with a very detailed rationale for the changes below. If there is an alternative preferred approach for this large-ish change I'm happy to restructure or break apart this PR as necessary.
cc @krisselden 
Note about terminology:
* **route** refers to a string that is added to the route recognizer (e.g.: the route in `router.add([{ path: '/foo/bar', ... }])` is `/foo/bar`)
* **path** refers to a string that will be given to the route recognizer to recognize (e.g. the path …
=> normalize route and path, encoded and decode dynamic path segments

lib/route-recognizer.js, tests/router-tests.js
re: https://github.com/tildeio/route-recognizer/pull/100
re: https://github.com/emberjs/ember.js/issues/13921
/cc @bantic @nathanhammond @jmeas @derrickshowers
It appears if two `charSpec`s share the same `validChars` (as dynamic segments and wildcards do, both `undefined`) then a later addition will stomp a pre-existing state. In this fix I've gotten more strict about equality (you can see in the code descending into child routes where it was already more exacting) and made this test pass, however I'm concerned about continuing to use `validChars` as a key for the cache of next states. It seems silly to even bother with the map when we can probably iterate just as fast. If iteration is too slow, then we should at least use a composite key with both `validChars` and `invalidChars`.
=> failing dynamic-versus-glob specificity est fix

tests/router-tests.js
*do not merge*
This failing test demonstrates the issue reported in https://github.com/emberjs/ember.js/issues/13921
This commit is the source of the test failure: https://github.com/tildeio/route-recognizer/commit/0499446f80c649a2df64ced5cc5458742a57c423
cc @jmeas
=> failing dynamic-versus-glob specificity est

lib/route-recognizer.js, tests/recognizer-tests.js
When adding an array of routes, each route will increase the
specificity instead of using only that of the last route.
Resolves #102.
=> Build up specificity for nested routes.

lib/route-recognizer.js, tests/recognizer-tests.js
https://github.com/tildeio/route-recognizer/pull/46 changed the specificity system used in route-recognizer to be much simpler, however the simpler implementation also lost some behaviors expected be real-world Ember apps. This introduces a test for such a case as reported in https://github.com/emberjs/ember.js/issues/13960 and rolls back the changes from #46.
=> Revert specificity changes in PR #46

lib/route-recognizer.js, lib/route-recognizer/normalizer.js, tests/recognizer-tests.js
During route generation for dynamic segments, do not percent-encode
characters that, according to RFC 3986, are allowed in path segments.
RFC 3986 defines "sub-delims" (these chars: `! $ & ' ( ) * + , ; =`) and
specifies that they along with `:` and `@` do not need to be encoded in path segments
in URIs. See: https://tools.ietf.org/html/rfc3986#section-3.3
This commit changes RouteRecognizer'ss generation code for dynamic
segments to explicitly avoid encoding those characters.
Fixes https://github.com/emberjs/ember.js/issues/14094
=> Do not encode chars that are allowed in path segments

lib/route-recognizer/normalizer.js
This approach is much simpler than walking the string, and appears to be
at least as performant as the previous.
Refs #109 
cc @nathanhammond
=> Use a regex in `encodePathSegment`

lib/route-recognizer/normalizer.js
Use a regex instead to replace any characters that shouldn't be decoded
(`%` and `/`) with their encoded form after decoding the rest of the
string.
As suggested via @krisselden in https://embercommunity.slack.com/?redir=%2Farchives%2Fdev-router%2Fp1471896246000705. cc @nathanhammond
=> Refactor `normalizeSegment` to avoid walking the string

lib/route-recognizer.js, tests/recognizer-tests.js
As identified by Vaanan Vetrivel Kannan, we don't currently handle path length correctly when dealing with encoded characters.
This adds a failing test and a fix.
=> Trailing slashes with encoded characters.

lib/route-recognizer.js, tests/recognizer-tests.js
route-recognizer forces both [dynamic segments](https://github.com/tildeio/route-recognizer/blob/master/lib/route-recognizer.js#L62) and [glob segments](https://github.com/tildeio/route-recognizer/blob/master/lib/route-recognizer.js#L81) to always be at least one character long at match time. [This has been the case since the dawn of time. ](https://github.com/tildeio/route-recognizer/blame/4feb8d58e8125725f881185881a4eb56d28ab563/lib/router.js#L54)
Three lines below each of those in the `generate` function we find that there are _no_ checks to prevent generation of a URL which route-recognizer is unable to recognize.
Proposed solution: we should throw an error during dynamic and glob route generation if the parameter is an empty string.
(Issue reported by @meirish.)
=> Throws errors when params would result in problems.

bench/benches/generate.js, bench/benches/handlers-for.js, package.json
Benchmarks no longer worked as a consequence of not having `glob` as a dependency and changes in allowed invocation patterns. These are also slightly more realistic benchmarks.
=> Fix benchmarks.

lib/route-recognizer.ts
handler.{names,shouldDecodes} are often empty, we shouldn’t bother allocating them if they are.
These are very very often empty arrays, we shouldn't alloc/iterate them if we don't need to.
---
Tests are red, I need to actually see yet if this is tannable.
=> Avoid extra allocations

lib/route-recognizer.ts
To be able to type router.js we need to expose `Delegate` as `Router` can take a route-recognizer delegate as an option.
=> Expose Delegate interface

lib/route-recognizer.ts
Router.js allows you to pass a the RR map callback in so we need to expose it.
=> Expose router map callback type

README.md
As of 2.2.0 the size of the route-recognizer library is 13.3 kB (minified) and 3.9 kB (minigied gzipped). This PR updates the size information in the README.md file.
Fixes #141
=> update the library size in README.md
